# Generated by Django 5.2.4 on 2025-08-11 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text='Numer telefonu opiekuna w formacie międzynarodowym, np. +48...', max_length=16, validators=[django.core.validators.RegexValidator(message='Podaj numer w formacie międzynarodowym, np. +48123123123.', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
