# Generated by Django 5.2.4 on 2025-08-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='frequency_per_day',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
    ]
