# Generated by Django 5.2.4 on 2025-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_medication_dosage_ml_per_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość leku na dawkę (np. 2 tabletki/ml)'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Ilość tabletek'),
        ),
    ]
