# Generated by Django 5.2.4 on 2025-08-07 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_medication_dosage_amount_alter_medication_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
